### PR TITLE
CANTINA-996: Remove restrictions that already exist in Parker & MU

### PR DESCRIPTION
**Pull request by rebeccahum**

### CODE REVIEW

**Comment by WPprodigy** [comment]
Cross-checked with https://github.com/Automattic/vip-go-api-public/blob/f8b13e30dc055b79b76aa655c43da0345af0041f/src/utils/wp-cli/commandValidator.js, looks good and covers everything intended by this code. The blocks here also have some errors in it, like how it handles languages and a non-existing `vip support-user`. The blocks in Parker all look correct and are more fine-tuned. Is also drastically easier to deploy updates to Parker than it is here.

**Comment by WPprodigy** [comment]
CC @nickdaugherty just to make sure we're not missing something here security-wise.

**Review by WPprodigy — APPROVED** [review]

**Comment by nickdaugherty** [comment]
Let's leave most of the validation, it's a good safeguard for our validation elsewhere.

**Review by WPprodigy — APPROVED** [review]
I think we're good to continue on with this, and finally standardize these blocks into one place rather than 3.

**Pull request merged**
